---
name: Documentation Bug
description: "🐞 Create a report to help us improve docs"
body:
  - type: markdown
    attributes:
      value: |
        Bug Report issues are for **concrete, actionable bugs** only.

  - type: checkboxes
    id: terms
    attributes:
      label: Please confirm the following
      options:
        - label: I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Briefly describe the problem with the existing documentation.
    validations:
      required: false

  - type: input
    id: guide
    attributes:
      label: Guide Affected
      options:
        - label: Administraton
        - label: User Guide
        - label: API Swagger
        - label: Other
    validations:
      required: true

  - type: textfield
    id: section
    attributes:
      label: Documentation section
      description: Specify the section of the document selected above
    validations:
      required: true

  - type: textfield
    id: version
    attributes:
      label: Documentation version
      description: Specify the version of the documentation this affects or `all`
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Requested changes
      description: How should the docs be changed to correct this issue?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce in AWX/Tower/etc
      description: >-
        Starting from a new installation of the system, describe how in the product to show the correct behavior.
    validations:
      required: true

  - type: textarea
    id: screen-shots
    attributes:
      label: Screenshots
      description: Add any new or changing screenshots for the document.
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Add any other context about the bug here.
    validations:
      required: false
